### PR TITLE
Adds dct using vDSP_DCT for Vector{Float32}

### PR DESCRIPTION
**Pull request by dlfivefifty**
This implements dct using Accelerate's vDSP_DCT routine.  As far as I know, there is only a single precision implementation.

I also fixed the unit tests.

I tried to implement the FFT as well (which supports double precision), but the currently commented out code causes a segment fault.  I'm not sure the correct way to pass in a pointer to a C struct

typedef struct DSPDoubleSplitComplex {
    double *realp;
    double *imagp;
} DSPDoubleSplitComplex;

 I tried creating what I thought would be the equivalent data structure to DSPDoubleSplitComplex*:

immutable DSPDoubleSplitComplex
     realp::Ptr{Float64}
     imagp::Ptr{Float64}
end

### CODE REVIEW

**Comment by simonbyrne** [comment]
Thanks! I'm a bit busy at the moment, but I'll try to look at the FFT next week.

**Comment by simonbyrne** [comment]
I just had a quick look over this: maybe we should change the `plan_dct` name, as it isn't quite a drop-in replacement for Julia's `plan_dct` (for one thing, it returns a pointer, whereas Julia's is purely a side-effect).

**Comment by dlfivefifty** [comment]
Maybe it should return a new Julia type, so that 

	P=plan_dct(2^4,1)
	P*rand(Float32,2^4)


works?   The dct’s are also slightly different normalizations.  So maybe the dct should be renamed as well?

**Comment by simonbyrne** [comment]
Yeah, good idea (I was hoping to see something like this in the new Julia FFT interface, whenever that gets merged).

**Comment by dlfivefifty** [comment]
That is how the new FFT interface works, in 0.4rc:


	v=rand(64)
	P=plan_fft(v)
	P*v

**Comment by simonbyrne** [comment]
Ah, I didn't realise it had been changed.  Yes, I think we should make a `vDSPPlan` type.

**Pull request merged**
