### PR TITLE
Ported testing to BaseTestNext

### PR DESCRIPTION
**Pull request by rprechelt**
I ported all of the testing over to `BaseTestNext`; they pass reliably on my local machine (we will have to see what Travis says). 

Travis Results:
- v0.4: Build completes and all tests pass
- nightly: Still failing `@replaceBase.sin` test.

### CODE REVIEW

**Comment by simonbyrne** [comment]
I think we can safely deprecate 0.3 support. I'll tag a last version now, and then you can bump the require file, and remove the line from .travis.yml.

**Comment by rprechelt** [comment]
Ok; I've updated .travis.yml and the require file to drop support for v0.3 All of the tests still pass on v0.4, but `replaceBase` `sin` test still fails on Travis, but not on any of my local machines. I'm at a loss for why this is occurring; if you have any suggestions, I can look into them before we merge.

**Comment by simonbyrne** [comment]
This is the same test that was causing the problem in #6. I'll merge it for now, as it still passes on 0.4, and we can figure this out later.

Thanks!

**Comment by rprechelt** [comment]
@tkelman  I'll make the change in my other open PR.

**Pull request merged**
