### PR TITLE
Convolution + Corrrelation + Types for Testing

### PR DESCRIPTION
**Pull request by rprechelt**
Another PR! This one contains the following:

1. `conv`: Convolution for Float64 and Float32 (initial profiling indicates that AppleAccelerate.conv is 23 times faster than `Base.conv`, and allocates 6 times less memory, for two arrays of length 100)
2. `xcorr`: Cross-correlation and auto-correlation for Float32 and Float64
3. Tests for the above functions for both types. I also noticed that the existing test suite did not contain testing for Float32. I made further enhancements to the existing tests so that they explicitly run on Float32 and Float64 and that this information is included in any error messages that are produced. 

**Travis Results**
2. v0.4: All tests pass.
3. v0.5: The `sin` test in `@replaceBase` (the start of all of this testing rewrite) still fails on Travis; *all* other tests pass. I've run it on three separate machines on both OS X and Ubuntu and the test always passes for me. At this point, I'm at a loss as for why it is failing in Travis but not locally. If you have any advice here, it would be most appreciated. 

Updated the .travis.yml per tkelman's suggestion (this is the cause of the merge).

### CODE REVIEW

**Comment by simonbyrne** [comment]
This needs to be rebased against the master branch.

**Comment by rprechelt** [comment]
Will do; probably have it done tomorrow.

**Comment by rprechelt** [comment]
Rebased.

**Comment by simonbyrne** [comment]
Fantastic, thanks!

**Comment by simonbyrne** [comment]
@rprechelt I've added you as a collaborator, so you now have commit access.

**Comment by rprechelt** [comment]
@simonbyrne thanks for the collaborator status! I have a couple of features already in mind that I am going to start working on next week; totally committed to making this package be as good as can be!

**Comment by tkelman** [comment]
First tagged version that includes this change to minimum julia version in `REQUIRE` should use a new package minor version number via `Pkg.tag("AppleAccelerate", :minor)`.

**Comment by simonbyrne** [comment]
Done: see https://github.com/JuliaLang/METADATA.jl/pull/4742

**Pull request merged**
